/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sat Dec 10 10:46:01 2016. */

#include "phillipshue.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PhillipsHue_fields[15] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, PhillipsHue, on, on, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, PhillipsHue, bri, on, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, PhillipsHue, hue, bri, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, PhillipsHue, sat, hue, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, PhillipsHue, effect, sat, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, PhillipsHue, ct, effect, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, CALLBACK, OTHER, PhillipsHue, alert, ct, 0),
    PB_FIELD(  8, DOUBLE  , REPEATED, STATIC  , OTHER, PhillipsHue, xy, alert, 0),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, PhillipsHue, transitiontime, xy, 0),
    PB_FIELD( 10, INT32   , OPTIONAL, STATIC  , OTHER, PhillipsHue, bri_inc, transitiontime, 0),
    PB_FIELD( 11, INT32   , OPTIONAL, STATIC  , OTHER, PhillipsHue, hue_inc, bri_inc, 0),
    PB_FIELD( 12, INT32   , OPTIONAL, STATIC  , OTHER, PhillipsHue, sat_inc, hue_inc, 0),
    PB_FIELD( 13, DOUBLE  , REPEATED, STATIC  , OTHER, PhillipsHue, xy_inc, sat_inc, 0),
    PB_FIELD( 14, INT32   , OPTIONAL, STATIC  , OTHER, PhillipsHue, ct_inc, xy_inc, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
