/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Sat Dec 10 10:46:01 2016. */

#ifndef PB_PHILLIPSHUE_PB_H_INCLUDED
#define PB_PHILLIPSHUE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _PhillipsHue {
    bool has_on;
    bool on;
    bool has_bri;
    int32_t bri;
    bool has_hue;
    int32_t hue;
    bool has_sat;
    int32_t sat;
    pb_callback_t effect;
    bool has_ct;
    int32_t ct;
    pb_callback_t alert;
    pb_size_t xy_count;
    double xy[2];
    bool has_transitiontime;
    int32_t transitiontime;
    bool has_bri_inc;
    int32_t bri_inc;
    bool has_hue_inc;
    int32_t hue_inc;
    bool has_sat_inc;
    int32_t sat_inc;
    pb_size_t xy_inc_count;
    double xy_inc[2];
    bool has_ct_inc;
    int32_t ct_inc;
/* @@protoc_insertion_point(struct:PhillipsHue) */
} PhillipsHue;

/* Default values for struct fields */

/* Initializer values for message structs */
#define PhillipsHue_init_default                 {false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, 0, {0, 0}, false, 0, false, 0, false, 0, false, 0, 0, {0, 0}, false, 0}
#define PhillipsHue_init_zero                    {false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, 0, {0, 0}, false, 0, false, 0, false, 0, false, 0, 0, {0, 0}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PhillipsHue_on_tag                       1
#define PhillipsHue_bri_tag                      2
#define PhillipsHue_hue_tag                      3
#define PhillipsHue_sat_tag                      4
#define PhillipsHue_effect_tag                   5
#define PhillipsHue_ct_tag                       6
#define PhillipsHue_alert_tag                    7
#define PhillipsHue_xy_tag                       8
#define PhillipsHue_transitiontime_tag           9
#define PhillipsHue_bri_inc_tag                  10
#define PhillipsHue_hue_inc_tag                  11
#define PhillipsHue_sat_inc_tag                  12
#define PhillipsHue_xy_inc_tag                   13
#define PhillipsHue_ct_inc_tag                   14

/* Struct field encoding specification for nanopb */
extern const pb_field_t PhillipsHue_fields[15];

/* Maximum encoded size of messages (where known) */
/* PhillipsHue_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PHILLIPSHUE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
